# Generated by Django 4.0.6 on 2022-07-08 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=20)),
                ('ie', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_funcionario', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=200)),
                ('senha', models.IntegerField(default=0)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pontos.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(max_length=100)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pontos.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroPontos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ponto_data', models.DateTimeField(verbose_name='Data do Ponto')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pontos.funcionario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pontos.usuario')),
            ],
        ),
    ]
