# Generated by Django 4.0.6 on 2022-07-08 13:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pontos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropontos',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ie',
            field=models.CharField(blank=True, max_length=10, verbose_name='IE'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome_empresa',
            field=models.CharField(max_length=100, verbose_name='Nome da Empresa'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='horario',
            field=models.CharField(max_length=200, verbose_name='Horário'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome_funcionario',
            field=models.CharField(max_length=100, verbose_name='Nome do Funcionário'),
        ),
        migrations.AlterField(
            model_name='registropontos',
            name='ponto_data',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 8, 13, 21, 13, 685917, tzinfo=utc), verbose_name='Data do Ponto'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome_usuario',
            field=models.CharField(max_length=100, verbose_name='Usuário'),
        ),
    ]
